meta_product_name: "Let's Curate"
meta_title: "Let's Curate - Put your art on the world's canvas"
meta_description: "Join the dream team, collaborate together and rise to fame !"
meta_image: "https://res.cloudinary.com/dmnigpnke/image/upload/v1496837982/cover_jphewf.png"
